### ISSUE TITLE
Add cancellation support

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-ddsfiletype-plus#5]
`FileTypeOptions.SupportsCancellation`, which adds the possibility of `OperationCanceledException`s being thrown from both the `Stream` and `ProgressEventHandler`, would make the user experience better. Happy to implement this myself if you'd like.

**Comment by 0xC0000054** [comment]
The Stream I/O callbacks already support cancellation as part of the general exception handling.

I added support for progress callback cancellation in commit 3ac23fa99c41b4d191d068906758d8f004080c13.

The only issue I encountered with the progress callback cancellation is that the multi-threaded CPU encoder will take longer to stop because OpenMP 2.0 does not support breaking out of a `parallel for` loop.
